### ISSUE TITLE
Lua Error if joining a group now

### ISSUE THREAD

**Issue by Jaidy88** [Isselbaecher/EnhancedMythicPlusLoot#10]
thank you very much for the quick implementation. so far the list has not reset itself. however, with the new patch i now get lua errors when i join a group or other players join a raid

_Originally posted by @Isselbaecher in https://github.com/Isselbaecher/EnhancedMythicPlusLoot/issues/8#issuecomment-2351505486_
            

32x EnhancedMPlusLoot/loottables.lua:150: attempt to compare number with string
[string "@EnhancedMPlusLoot/loottables.lua"]:150: in function `?'
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 dungeonIDs = <table> {
 }
 modules = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
 specId = 257
 db = <table> {
 }
 enabledState = true
 seasonNames = <table> {
 }
 lootContainer = <table> {
 }
 scroll = <table> {
 }
 specNum = 2
 playerClassId = 5
 baseName = "EnhancedMPlusLoot"
 defaultModuleLibraries = <table> {
 }
 name = "EnhancedMPlusLoot"
 orderedModules = <table> {
 }
 showLootFrame = false
 defaultSeasonId = 13
 lootContainerRows = <table> {
 }
 menu = Frame {
 }
 L = <table> {
 }
}
delay = "PLAYER_SPECIALIZATION_CHANGED"
maxTries = "party4"
currentTry = 1
mplusActive = true
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with string"

**Comment by Isselbaecher** [comment]
Thanks for your bug report - it should be fixed now :)
