### ISSUE TITLE
Random issues I found & suggestions

### ISSUE THREAD

**Issue by KurtzPT** [Isselbaecher/EnhancedMythicPlusLoot#3]
Latest version when this post was made was used.

So if I open and close multiple times the looking for group (keybind i) window. Multiple windows of EnhancedMythicPlusLoot will appear (they usually stack one above the other). Also the same EnhancedMythicPlusLoot window will not close when I close looking for group window.

Same issue will occur when I have the looking for group window opened and I try to track another item in the EnhancedMythicPlusLoot config. Everytime it will pop-up another window.

Lastly, this window is empty and does not show any of the items I added to the tracking list.

**Comment by KurtzPT** [comment]
Some suggestions: The window pop-up will never save the previous size and position I gave to it. It should do that or at least have an option to allow us to define this window settings.

**Comment by Isselbaecher** [comment]
Which version did you use?
0.3.3.1 has those bugs fixxed and all of your requested features.

The instant "Fetch loot - success" without retrying is done from the db, not from the Adventure Journal (WoW API).
I'll change the chat output to better differentiate where the data is coming from.

**Comment by KurtzPT** [comment]
According to CurseForge I'm using 0.3.3.1. I even re-installed from curseforge and same issues happen.

**Comment by Isselbaecher** [comment]
Strange. Any lua errors on wow startup or opening the addon?
I've tested on Live, PTR, and Beta (Live with other addons, PTR & Beta with only this addon) and I can not reproduce the issue.
Which class are you playing? At what level? Maybe I can reproduce the issue with a test character.

**Comment by KurtzPT** [comment]
So I disabled all my addons except ElvUI and it works now. The issues do not appear and the loot that I'm tracking appears. Saving the position/size of the window still does not but I assume that is not yet implemented.

I'll try to figure what addon I have that causes an issue with it. I didn't get any lua errors.

**Comment by Isselbaecher** [comment]
If you find out which addon is causing the issue - please let me know - I will try to fix it :)
Thanks <3

**Comment by KurtzPT** [comment]
I'm dumb, I had LUA errors disabled. I get this error when the issue appears:

```
Message: .../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:356: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: Frame:SetPoint.
Time: Sat Jun  8 19:16:14 2024
Count: 1
Stack: .../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:356: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: Frame:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:356: in function `SetPoint'
[string "@Interface/AddOns/EnhancedMPlusLoot/lootframe.lua"]:21: in function `CreateLootFrame'
[string "@Interface/AddOns/EnhancedMPlusLoot/lootframe.lua"]:135: in function `ShowLootFrame'
[string "@Interface/AddOns/EnhancedMPlusLoot/lootframe.lua"]:155: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:90: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:87>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:458: in function `SetUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:301: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:165: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:161>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:769: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/PVEFrame.lua"]:97: in function `PVEFrame_ShowFrame'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/PVEFrame.lua"]:55: in function <...ce/AddOns/Blizzard_GroupFinder/Mainline/PVEFrame.lua:31>
[string "=[C]"]: in function `PVEFrame_ToggleFrame'
[string "TOGGLEGROUPFINDER"]:1: in function <[string "TOGGLEGROUPFINDER"]:1>

Locals: (*temporary) = <function> defined =[C]:-1
```

**Comment by KurtzPT** [comment]
Found the culprit. The addon is [ElvUI Windtools](https://github.com/fang2hou/ElvUI_WindTools)

**Comment by KurtzPT** [comment]
I even found out what option in Windtools makes this issue appear. When enabling the following:

![image](https://github.com/Isselbaecher/EnhancedMythicPlusLoot/assets/14930057/00ad4413-072f-4c89-be83-b22dcb4fa313)

**Comment by Isselbaecher** [comment]
I think occurs, because I anchor to PVEFrame and something is intercepting the PVEFrame.
I'll just anchor to UIParent and save the position of the loot-tracking frame. 
But it will probably take a day or two to test and push the fix.

The main window (not the one on the PVEFrame) should already save size and position.
Does it do that for you (With the drag and drop setting enabled/disabled?)
If not I'll install ElvUI and Windtools on PTR and try to fix that too :)

Thanks for all the investigating :)

**Comment by KurtzPT** [comment]
When I disable the Move Frames option in Windtools, the MythicPlusLoot tracking window will never remember the position I set to. Example:

I move the window like this:

![image](https://github.com/Isselbaecher/EnhancedMythicPlusLoot/assets/14930057/ebe4ffff-9c96-451f-baef-0aace8932b0b)

But after closing and opning again, it will go to the default location:

![image](https://github.com/Isselbaecher/EnhancedMythicPlusLoot/assets/14930057/614df321-efa3-4b08-8c2b-e4dc99c38b7c)

Of couse with the Move Frames option turned on in Windtools, the window doesn't work at all it gives that big lua error.

**Comment by Isselbaecher** [comment]
Perfect - then I can make the small window do it :)

**Comment by Isselbaecher** [comment]
Pushed a fix, that should solve your ploblem.
Also the small loot tracke window will now be moveable by default and remember it's position.
Let me kmow if everything works as expected in version 0.3.3.3 :)

**Comment by KurtzPT** [comment]
It's working perfectly now! It even makes the loot search with the "AND" clause. Thanks for the updates!
