### ISSUE TITLE
Reasonable suggestions

### ISSUE THREAD

**Issue by gt1226500986** [Isselbaecher/EnhancedMythicPlusLoot#5]
There is a plug-in:https://www.curseforge.com/wow/addons/keystoneloot
Its function is very similar to yours, it should be able to view group copies and packages，Do you know if you will add it later?

**Comment by Isselbaecher** [comment]
I do not get what functionality you are describing.
Could you describe that a little bit more please?

**Comment by Isselbaecher** [comment]
Closed until further explanation.
