### ISSUE TITLE
my activated items are constantly being reset and the list is empty

### ISSUE THREAD

**Issue by Jaidy88** [Isselbaecher/EnhancedMythicPlusLoot#8]
How is it that my desired items are suddenly all unchecked and I have to check all the items again and again just because the M+ season hasn't started yet? or what am I doing wrong?

**Comment by Isselbaecher** [comment]
Found the error - the addon was loading too fast and C_MythicPlus.IsMythicPlusActive() was returning false on load, but true later - which caused the addon to reset loot data.
I've pushed a fix to 0.5.5-Release which should go up in the next minutes.

Thank you for the error report <3
